name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get


      - name: Build APK (Fat APK)
        run: flutter build apk --release --split-per-abi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release-b${{ github.run_number }}"
          files: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          name: "Automatic Release - Build #${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
